const pages={
home:{title:"Visão Geral",sub:"Painel de gestão à vista da operação",html:home()},
safety:{title:"Momento de Segurança",sub:"Mensagem e foco de segurança do dia",html:safety()},
oee:{title:"OEE / Eficiência",sub:"Acompanhamento de desempenho por linha e turno",html:oee()},
production:{title:"Produção em Tempo Real",sub:"Plano x realizado e ritmo da operação",html:production()},
people:{title:"Absenteísmo",sub:"Acompanhamento de presença e disponibilidade de mão de obra",html:people()},
quality:{title:"Qualidade / Não Qualidade",sub:"Scrap, retrabalho, defeitos e Pareto",html:quality()}
};
function shell(p){return '<div class="page"><div class="page-head"><div><h1>'+p.title+'</h1><p>'+p.sub+'</p></div><div class="refresh">● Atualização: automática</div></div>'+p.html+'</div>'}
function card(label,value,cls=""){return '<div class="card"><div class="label">'+label+'</div><div class="value '+cls+'">'+value+'</div></div>'}
function home(){return '<div class="hero-status"><div class="status"><span class="dot green"></span> OPERAÇÃO NORMAL</div><p style="margin:8px 0 0;color:#47616f">Visão consolidada — Segurança, Pessoas, Produção, OEE e Qualidade.</p></div><div class="cards">'+card("OEE Geral","85,4%","good")+card("Eficiência","89,8%","good")+card("Produção","12.480","")+card("Qualidade","98,5%","good")+card("Absenteísmo","3,2%","warn")+'</div><div class="section-grid"><div class="panel"><h2>Produção por linha</h2><table><tr><th>Linha</th><th>Plano</th><th>Real</th><th>Ating.</th><th>Status</th></tr><tr><td>AL1</td><td>4.500</td><td>4.320</td><td>96%</td><td><span class="status"><span class="dot yellow"></span>Atenção</span></td></tr><tr><td>AL2</td><td>4.200</td><td>4.450</td><td>106%</td><td><span class="status"><span class="dot green"></span>OK</span></td></tr><tr><td>AL3</td><td>3.800</td><td>3.710</td><td>98%</td><td><span class="status"><span class="dot green"></span>OK</span></td></tr></table></div><div class="panel"><h2>Momento de Segurança</h2><div class="safety-img" style="min-height:180px"><div><div class="shield">🦺</div><h2>SEGURANÇA EM PRIMEIRO LUGAR</h2><div>Use os EPIs e respeite as áreas demarcadas.</div></div></div></div></div>'}
function safety(){return '<div class="safety-card"><div class="safety-img"><div><div class="shield">🦺</div><div style="font-size:12px;letter-spacing:2px">MOMENTO DE SEGURANÇA • HOJE</div><h2>SEGURANÇA EM PRIMEIRO LUGAR</h2><p>Use os EPIs corretos, mantenha atenção ao entorno e nunca realize intervenção sem bloqueio seguro.</p></div></div><div class="panel"><h2>Foco do dia</h2><div class="mini"><div class="label">Tema</div><strong>Segurança com máquinas</strong></div><div class="mini" style="margin-top:10px"><div class="label">Comportamento esperado</div><strong style="font-size:16px">Parar, bloquear e verificar antes de intervir.</strong></div><div class="mini" style="margin-top:10px"><div class="label">Responsável</div><strong style="font-size:16px">Liderança da área</strong></div></div></div><div class="panel" style="margin-top:18px"><h2>Histórico dos últimos dias</h2><table><tr><th>Data</th><th>Tema</th><th>Área</th><th>Status</th></tr><tr><td>06/10</td><td>Segurança com máquinas</td><td>Fundição</td><td>🟢 Realizado</td></tr><tr><td>05/10</td><td>Uso de EPI</td><td>Injeção</td><td>🟢 Realizado</td></tr><tr><td>04/10</td><td>Ergonomia</td><td>Acabamento</td><td>🟢 Realizado</td></tr></table></div>'}
const oeeData=[
{area:"Fundição",linha:"AL1",turno:"A",oee:91.0,disp:94.0,perf:97.0,qual:99.0,ef:91.0,meta:85},
{area:"Fundição",linha:"AL1",turno:"B",oee:86.0,disp:91.0,perf:95.0,qual:99.0,ef:87.0,meta:85},
{area:"Fundição",linha:"AL2",turno:"A",oee:78.0,disp:88.0,perf:91.0,qual:97.0,ef:78.0,meta:85},
{area:"Fundição",linha:"AL2",turno:"B",oee:82.0,disp:89.0,perf:94.0,qual:98.0,ef:82.0,meta:85},
{area:"Fundição",linha:"AL3",turno:"A",oee:86.0,disp:92.0,perf:94.0,qual:99.0,ef:86.0,meta:85},
{area:"Acabamento",linha:"AC1",turno:"A",oee:88.0,disp:93.0,perf:95.0,qual:99.0,ef:88.0,meta:85},
{area:"Acabamento",linha:"AC2",turno:"B",oee:84.0,disp:90.0,perf:94.0,qual:99.0,ef:84.0,meta:85},
{area:"Usinagem",linha:"US1",turno:"A",oee:89.0,disp:94.0,perf:95.0,qual:99.0,ef:89.0,meta:85},
{area:"Usinagem",linha:"US2",turno:"C",oee:87.0,disp:92.0,perf:95.0,qual:99.0,ef:87.0,meta:85}
];
function pct(v){return v.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})+"%"}
function oee(){
return '<div class="panel oee-filter-panel"><div class="oee-filter-head"><div><h2>Filtros de análise</h2><p>Selecione uma combinação ou mantenha “Toda a fábrica” para a visão consolidada.</p></div><button class="filter-reset" id="oeeReset">↺ Limpar filtros</button></div><div class="oee-filters"><label>Área<select id="oeeArea"><option value="Todas">Toda a fábrica</option><option>Fundição</option><option>Acabamento</option><option>Usinagem</option></select></label><label>Linha<select id="oeeLinha"><option value="Todas">Todas as linhas</option></select></label><label>Turno<select id="oeeTurno"><option value="Todos">Todos os turnos</option><option>A</option><option>B</option><option>C</option></select></label><label>Data<input id="oeeDate" type="date"></label><label>De<input id="oeeStart" type="time" value="00:00"></label><label>Até<input id="oeeEnd" type="time" value="23:59"></label></div><div class="filter-context" id="oeeContext">Visão consolidada • Todas as áreas, linhas e turnos</div></div><div class="cards" id="oeeCards"></div><div class="section-grid"><div class="panel"><h2>OEE por linha</h2><div id="oeeTable"></div></div><div class="panel"><h2>Comparativo de OEE</h2><div class="chart" id="oeeChart"></div><div class="footer-note">Meta de referência: 85% • Dados ilustrativos para demonstração.</div></div></div><div class="footer-note">Importante: os números exibidos nesta versão são demonstrativos. A conexão com dados reais do L2L ainda será implementada.</div>';
}
function updateOee(){
const area=document.getElementById("oeeArea").value, linha=document.getElementById("oeeLinha").value, turno=document.getElementById("oeeTurno").value, date=document.getElementById("oeeDate").value, start=document.getElementById("oeeStart").value, end=document.getElementById("oeeEnd").value;
const rows=oeeData.filter(x=>(area==="Todas"||x.area===area)&&(linha==="Todas"||x.linha===linha)&&(turno==="Todos"||x.turno===turno)&&(start<=end));
const avg=k=>rows.length?rows.reduce((s,x)=>s+x[k],0)/rows.length:0;
document.getElementById("oeeContext").textContent=(area==="Todas"?"Toda a fábrica":area)+" • "+(linha==="Todas"?"Todas as linhas":linha)+" • "+(turno==="Todos"?"Todos os turnos":"Turno "+turno)+" • "+(date?date.split("-").reverse().join("/"):"Todas as datas")+" • "+start+" → "+end+" • "+rows.length+" registro(s)";
document.getElementById("oeeCards").innerHTML=card("OEE",rows.length?pct(avg("oee")):"—",avg("oee")>=85?"good":"warn")+card("Disponibilidade",rows.length?pct(avg("disp")):"—","")+card("Performance",rows.length?pct(avg("perf")):"—","")+card("Qualidade",rows.length?pct(avg("qual")):"—","good")+card("Eficiência",rows.length?pct(avg("ef")):"—",avg("ef")>=85?"good":"warn");
document.getElementById("oeeTable").innerHTML=rows.length?'<table><tr><th>Área</th><th>Linha</th><th>Turno</th><th>Meta</th><th>OEE</th><th>Status</th></tr>'+rows.map(x=>'<tr><td>'+x.area+'</td><td>'+x.linha+'</td><td>'+x.turno+'</td><td>'+pct(x.meta)+'</td><td><b>'+pct(x.oee)+'</b></td><td><span class="status"><span class="dot '+(x.oee>=x.meta?"green":"red")+'"></span>'+(x.oee>=x.meta?"Meta atingida":"Abaixo da meta")+'</span></td></tr>').join("")+'</table>':'<p class="empty-state">Nenhum registro encontrado para essa combinação de filtros.</p>';
document.getElementById("oeeChart").innerHTML=rows.length?rows.map(x=>'<div class="col"><i style="--h:'+x.oee+'%"></i>'+x.linha+'<br><b>'+pct(x.oee)+'</b></div>').join(""):'<p class="empty-state">Sem dados para exibir.</p>';
}
function initOee(){
const area=document.getElementById("oeeArea"), linha=document.getElementById("oeeLinha"), turno=document.getElementById("oeeTurno"), date=document.getElementById("oeeDate"), start=document.getElementById("oeeStart"), end=document.getElementById("oeeEnd");
function updateLines(){const selected=linha.value;const available=[...new Set(oeeData.filter(x=>area.value==="Todas"||x.area===area.value).map(x=>x.linha))];linha.innerHTML='<option value="Todas">Todas as linhas</option>'+available.map(x=>'<option>'+x+'</option>').join("");if(available.includes(selected))linha.value=selected;else linha.value="Todas";}
area.addEventListener("change",()=>{updateLines();updateOee()});linha.addEventListener("change",updateOee);turno.addEventListener("change",updateOee);date.addEventListener("change",updateOee);start.addEventListener("change",updateOee);end.addEventListener("change",updateOee);
document.getElementById("oeeReset").addEventListener("click",()=>{area.value="Todas";turno.value="Todos";date.value="";start.value="00:00";end.value="23:59";updateLines();linha.value="Todas";updateOee()});
updateLines();updateOee();
}
const productionData=[
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-05",start:"07:00",end:"08:00",plan:900,real:850},
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-05",start:"08:00",end:"09:00",plan:900,real:875},
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-05",start:"09:00",end:"10:00",plan:900,real:920},
{area:"Fundição",linha:"AL2",turno:"A",date:"2026-10-05",start:"07:00",end:"08:00",plan:850,real:810},
{area:"Fundição",linha:"AL2",turno:"A",date:"2026-10-05",start:"08:00",end:"09:00",plan:850,real:830},
{area:"Fundição",linha:"AL3",turno:"A",date:"2026-10-05",start:"07:00",end:"08:00",plan:830,real:790},
{area:"Fundição",linha:"AL3",turno:"A",date:"2026-10-05",start:"08:00",end:"09:00",plan:830,real:760},
{area:"Acabamento",linha:"AC1",turno:"A",date:"2026-10-05",start:"08:00",end:"09:00",plan:780,real:790},
{area:"Usinagem",linha:"US1",turno:"A",date:"2026-10-05",start:"08:00",end:"09:00",plan:760,real:740},
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-06",start:"08:00",end:"09:00",plan:900,real:860},
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-06",start:"09:00",end:"10:00",plan:900,real:920},
{area:"Fundição",linha:"AL1",turno:"A",date:"2026-10-06",start:"10:00",end:"11:00",plan:900,real:880},
{area:"Fundição",linha:"AL2",turno:"A",date:"2026-10-06",start:"08:00",end:"09:00",plan:850,real:820},
{area:"Fundição",linha:"AL2",turno:"A",date:"2026-10-06",start:"09:00",end:"10:00",plan:850,real:870},
{area:"Fundição",linha:"AL3",turno:"A",date:"2026-10-06",start:"08:00",end:"09:00",plan:830,real:760},
{area:"Acabamento",linha:"AC1",turno:"A",date:"2026-10-06",start:"08:00",end:"09:00",plan:780,real:790},
{area:"Usinagem",linha:"US1",turno:"A",date:"2026-10-06",start:"08:00",end:"09:00",plan:760,real:740}
];
function production(){return '<div class="panel"><div class="oee-filter-panel"><div class="oee-filters"><label>Área<select id="prodArea"><option value="Todas">Toda a fábrica</option><option>Fundição</option><option>Acabamento</option><option>Usinagem</option></select></label><label>Linha<select id="prodLinha"><option value="Todas">Todas as linhas</option></select></label><label>Turno<select id="prodTurno"><option value="Todos">Todos os turnos</option><option>A</option><option>B</option><option>C</option></select></label><label>Data<input id="prodDate" type="date"></label><label>De<input id="prodStart" type="time" value="00:00"></label><label>Até<input id="prodEnd" type="time" value="23:59"></label></div><div class="filter-actions"><button class="filter-reset" id="prodReset">↺ Limpar filtros</button></div><div class="filter-context" id="prodContext"></div></div></div><div id="prodCards" class="cards"></div><div class="panel"><h2>Controle de produção — análise detalhada</h2><div id="prodTable"></div><div class="footer-note">Dados demonstrativos nesta primeira versão. A estrutura está preparada para receber os dados reais do L2L.</div></div>'}
function updateProduction(){const area=document.getElementById("prodArea").value,linha=document.getElementById("prodLinha").value,turno=document.getElementById("prodTurno").value,date=document.getElementById("prodDate").value,start=document.getElementById("prodStart").value,end=document.getElementById("prodEnd").value;let rows=productionData.filter(x=>(area==="Todas"||x.area===area)&&(linha==="Todas"||x.linha===linha)&&(turno==="Todos"||x.turno===turno)&&(!date||x.date===date)&&x.end>start&&x.start<end);const plan=rows.reduce((a,x)=>a+x.plan,0),real=rows.reduce((a,x)=>a+x.real,0),saldo=real-plan,ating=plan?real/plan*100:0,ritmo=rows.length?real/rows.length:0;document.getElementById("prodCards").innerHTML=card("Plano",plan.toLocaleString("pt-BR"))+card("Realizado",real.toLocaleString("pt-BR"))+card("Saldo",(saldo>=0?"+":"")+saldo.toLocaleString("pt-BR"),saldo>=0?"good":"bad")+card("Atingimento",ating.toFixed(1)+"%",ating>=100?"good":ating>=95?"warn":"bad")+card("Ritmo/h",Math.round(ritmo).toLocaleString("pt-BR"),"good");document.getElementById("prodContext").textContent=(area==="Todas"?"Toda a fábrica":area)+" • "+(linha==="Todas"?"Todas as linhas":linha)+" • "+(turno==="Todos"?"Todos os turnos":"Turno "+turno)+" • "+(date?date.split("-").reverse().join("/"):"Todas as datas")+" • "+start+" → "+end+" • "+rows.length+" registro(s)";document.getElementById("prodTable").innerHTML=rows.length?'<table><tr><th>Área</th><th>Linha</th><th>Turno</th><th>Período</th><th>Plano</th><th>Realizado</th><th>Saldo</th><th>Ating.</th><th>Status</th></tr>'+rows.map(x=>{const s=x.real-x.plan,p=x.real/x.plan*100;return '<tr><td>'+x.area+'</td><td><b>'+x.linha+'</b></td><td>'+x.turno+'</td><td>'+x.start+'–'+x.end+'</td><td>'+x.plan.toLocaleString("pt-BR")+'</td><td>'+x.real.toLocaleString("pt-BR")+'</td><td>'+(s>=0?"+":"")+s.toLocaleString("pt-BR")+'</td><td>'+p.toFixed(1)+'%</td><td>'+(p>=100?"🟢":p>=95?"🟡":"🔴")+'</td></tr>'}).join("")+'</table>':'<div class="empty-state">Nenhum registro encontrado para os filtros selecionados.</div>'}
function initProduction(){const area=document.getElementById("prodArea"),linha=document.getElementById("prodLinha"),turno=document.getElementById("prodTurno"),date=document.getElementById("prodDate"),start=document.getElementById("prodStart"),end=document.getElementById("prodEnd");function updateLines(){const a=area.value;linha.innerHTML='<option value="Todas">Todas as linhas</option>'+[...new Set(productionData.filter(x=>a==="Todas"||x.area===a).map(x=>x.linha))].map(x=>'<option>'+x+'</option>').join("")}area.addEventListener("change",()=>{updateLines();updateProduction()});[linha,turno,date,start,end].forEach(x=>x.addEventListener("change",updateProduction));document.getElementById("prodReset").addEventListener("click",()=>{area.value="Todas";turno.value="Todos";date.value="";start.value="00:00";end.value="23:59";updateLines();linha.value="Todas";updateProduction()});updateLines();updateProduction()}
function people(){return '<div class="cards">'+card("Absenteísmo","3,2%","warn")+card("Presentes","94,8%","good")+card("Faltas","11","bad")+card("Afastamentos","4","warn")+card("Efetivo","342")+'</div><div class="panel"><h2>Absenteísmo por área</h2><table><tr><th>Área</th><th>Efetivo</th><th>Ausentes</th><th>%</th><th>Indicador</th></tr><tr><td>Fundição</td><td>120</td><td>4</td><td>3,3%</td><td><div class="bar"><i style="width:33%"></i></div></td></tr><tr><td>Injeção</td><td>85</td><td>2</td><td>2,4%</td><td><div class="bar"><i style="width:24%"></i></div></td></tr><tr><td>Usinagem</td><td>110</td><td>5</td><td>4,5%</td><td><div class="bar"><i style="width:45%"></i></div></td></tr></table></div>'}
function quality(){return '<div class="cards">'+card("Qualidade","98,5%","good")+card("Scrap","1,5%","good")+card("Retrabalho","2,1%","warn")+card("PPM","185","warn")+card("NQ","R$ 12,4 mil","bad")+'</div><div class="section-grid"><div class="panel"><h2>Pareto de defeitos</h2><table><tr><th>Defeito</th><th>%</th><th>Representação</th></tr><tr><td>Porosidade</td><td>38%</td><td><div class="bar"><i style="width:38%"></i></div></td></tr><tr><td>Rebarba</td><td>21%</td><td><div class="bar"><i style="width:21%"></i></div></td></tr><tr><td>Trinca</td><td>15%</td><td><div class="bar"><i style="width:15%"></i></div></td></tr><tr><td>Dimensional</td><td>12%</td><td><div class="bar"><i style="width:12%"></i></div></td></tr></table></div><div class="panel"><h2>Não qualidade por processo</h2><div class="kpis"><div class="mini"><div class="label">Injeção</div><strong>42%</strong></div><div class="mini"><div class="label">Acabamento</div><strong>31%</strong></div><div class="mini"><div class="label">Usinagem</div><strong>18%</strong></div></div></div></div>'}
function render(page){document.getElementById("content").innerHTML=shell(pages[page]);if(page==="oee")initOee();if(page==="production")initProduction()}
document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.page)}));
function tick(){const d=new Date();document.getElementById("date").textContent=d.toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});document.getElementById("time").textContent=d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
render("home");tick();setInterval(tick,1000);
